CREATE TABLE IF NOT EXISTS regions (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    region_id SMALLINT NOT NULL,
    name VARCHAR(15) NOT NULL
);

ALTER TABLE regions ADD CONSTRAINT pk_regions PRIMARY KEY (id);

INSERT INTO
    regions (region_id, name)
VALUES (1, 'Region I'),
    (2, 'Region II'),
    (3, 'Region III'),
    (4, 'CALABARZON'),
    (5, 'MIMAROPA'),
    (6, 'Region V'),
    (7, 'Region VI'),
    (8, 'Region VII'),
    (9, 'Region VIII'),
    (10, 'Region IX'),
    (11, 'Region X'),
    (12, 'Region XI'),
    (13, 'Region XII'),
    (14, 'Caraga'),
    (15, 'BARMM'),
    (16, 'CAR'),
    (17, 'NCR');