services:
  app:
    build:
      context: .
      dockerfile: ./dev.dockerfile
      args:
        - APP_PORT=${APP_PORT}
    container_name: ptms_app
    environment:
      - APP_KEY=${APP_KEY}
      - APP_ENV=${APP_ENV}
      - APP_PORT=${APP_PORT}
      - DB_DRIVER=${DB_DRIVER}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - .:/app:Z
    ports:
      - 8888:8888
    depends_on:
      - db

  db:
    image: postgres:16-bookworm
    container_name: ptms_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf:Z

  proxy:
    image: nginx:1.26.2-bookworm
    container_name: ptms_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:Z
      - ./assets:/app:Z
    depends_on:
      - app