// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Activity struct {
	ID        int32
	Title     string
	StartDate time.Time
	EndDate   time.Time
	Venue     sql.NullString
	Host      sql.NullString
	Metadata  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type Office struct {
	ID        int32
	Name      string
	Metadata  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type Personnel struct {
	ID         int32
	Lastname   string
	Firstname  string
	Mi         sql.NullString
	PositionID int16
	OfficeID   sql.NullInt16
	Metadata   json.RawMessage
	CreatedAt  time.Time
	UpdatedAt  time.Time
	IsDeleted  bool
}

type Position struct {
	ID        int32
	Title     string
	Metadata  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}

type Travel struct {
	ID         int32
	StartDate  time.Time
	EndDate    time.Time
	Status     int16
	Remarks    sql.NullString
	Metadata   json.RawMessage
	ActivityID int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	IsDeleted  bool
}
