// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Activity struct {
	ID        int32           `json:"id"`
	Title     string          `json:"title"`
	StartDate DateOnlyTime    `json:"start_date"`
	EndDate   DateOnlyTime    `json:"end_date"`
	Venue     NullString      `json:"venue"`
	Host      NullString      `json:"host"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
	IsDeleted bool            `json:"is_deleted"`
}

type Office struct {
	ID        int32           `json:"id"`
	Name      string          `json:"name"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
	IsDeleted bool            `json:"is_deleted"`
}

type Personnel struct {
	ID         int32           `json:"id"`
	Lastname   string          `json:"lastname"`
	Firstname  string          `json:"firstname"`
	Mi         sql.NullString  `json:"mi"`
	PositionID int16           `json:"position_id"`
	OfficeID   sql.NullInt16   `json:"office_id"`
	Metadata   json.RawMessage `json:"metadata"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
	IsDeleted  bool            `json:"is_deleted"`
}

type Position struct {
	ID        int32           `json:"id"`
	Title     string          `json:"title"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
	IsDeleted bool            `json:"is_deleted"`
}

type Travel struct {
	ID         int32           `json:"id"`
	StartDate  DateOnlyTime    `json:"start_date"`
	EndDate    DateOnlyTime    `json:"end_date"`
	Status     int16           `json:"status"`
	Remarks    NullString      `json:"remarks"`
	Metadata   json.RawMessage `json:"metadata"`
	ActivityID int32           `json:"activity_id"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
	IsDeleted  bool            `json:"is_deleted"`
}
