// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: regions.sql

package db

import (
	"context"
)

const getRegions = `-- name: GetRegions :many
SELECT id, region_id, name FROM regions ORDER BY region_id
`

func (q *Queries) GetRegions(ctx context.Context) ([]Region, error) {
	rows, err := q.db.QueryContext(ctx, getRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(&i.ID, &i.RegionID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
